In [3]:
import numpy as np

In [10]:
l1 = [1,2,3,4,5,6,7,8,9,10]

In [11]:
l2=[]
for i in range(1,11):
    l2.append(i)
print(l2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# 1-dimentional numpy array

In [12]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
l = range(1,1001)
print(l)

range(1, 1001)


In [16]:
%timeit [i**2 for i in l]

245 µs ± 4.77 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
a = np.arange(1,1001)
%timeit a**2

1.09 µs ± 6.56 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [21]:
a.ndim

1

In [22]:
a.shape

(5,)

In [23]:
len(a)

5

# 2-dimentional array

In [25]:
for i in range(1,3):
    for j in range(1,3):
        print(i, end="")
    print()

11
22


In [26]:
a = np.array([ [1,1],[2,2] ])
print(a)

[[1 1]
 [2 2]]


In [27]:
a.ndim

2

In [28]:
a.shape

(2, 2)

In [29]:
len(a)

2

In [30]:
a = np.array([[[0,1],[2,3]] , [[4,5],[6,7]]])
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a.ndim

3

In [32]:
a.shape

(2, 2, 2)

In [36]:
for i in range(5,101,5):
    print(i,end=" ")

5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 

In [37]:
a = np.arange(1,101,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [38]:
multipleof7 = np.arange(7,101, 7)
multipleof7

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [39]:
a = np.array([0,1])
a

array([0, 1])

In [42]:
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [43]:
0.5-0.25

0.25

In [44]:
0.25-0

0.25

In [46]:
1.0-0.75

0.25

In [50]:
a = np.linspace(1,100,5)
print(a)

[  1.    25.75  50.5   75.25 100.  ]


In [51]:
#ones matrix:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
a = np.diag([10,20,30,40])
a

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [55]:
a = np.random.rand(4)
a

array([0.3709947 , 0.27915987, 0.99384706, 0.40991104])

In [59]:
a.dtype

dtype('float64')

In [60]:
a = np.array([True, True, False , False])
a.dtype

dtype('bool')

In [61]:
a = np.array(["shravnya", "guru", "satish"])
print(a.dtype)

<U8


In [62]:
l1 = [1,2,3,4,5,6,7,8,9,10]
print(l1[0])

1


In [63]:
print(l1[5])

6


In [64]:
a = np.array([10,20,30,40,50])
print(a[0])

10


In [66]:
print(a[4])

50


In [67]:
a[0] = 100

In [68]:
print(a)

[100  20  30  40  50]


In [69]:
a[0:] = 500

In [70]:
print(a)

[500 500 500 500 500]


In [71]:
a = np.array([10,20,30,40,50])
print(a[0])

10


In [72]:
a[2:] = 500

In [73]:
print(a)

[ 10  20 500 500 500]


In [74]:
#two dimentional numpy array

a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [75]:
print(a[0,0])

1


In [76]:
print(a[0,3])

4


In [77]:
print(a[1,2])

7


In [78]:
print(a[0:])

[[1 2 3 4]
 [5 6 7 8]]


In [83]:
print(a[1:])

[[5 6 7 8]]


In [86]:
print(a[0::2])

[[1 2 3 4]]


In [87]:
print(a[1::2])

[[5 6 7 8]]
